//////////////////////////////////////////////////////////////////////////////
// Model: apollo_pi.qm
// File:  ./src/bsp.h
//
// This file has been generated automatically by QP Modeler (QM).
// DO NOT EDIT THIS FILE MANUALLY.
//
// Please visit www.state-machine.com/qm for more information.
//////////////////////////////////////////////////////////////////////////////
#ifndef bsp_h
#define bsp_h

#include <cstdint>

namespace ApolloPi {

uint32_t const BSP_TICKS_PER_SEC = static_cast<uint32_t>(1000);

} /* namespace ApolloPi */

#endif /* bsp_h */
